language: r
cache: packages
pandoc_version: 1.19.2.1

install:
  - Rscript -e 'install.packages('devtools')'
  - Rscript -e 'devtools::install_github('rstudio/bookdown')'

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
