# R y RStudio

``R`` es un lenguaje de programación de código abierto usado ampliamente para estadística, minería de datos, y desarrollo de software. ``RStudio`` es un entorno de desarrollo integrado (IDE) para ``R``. Puesto en otras palabras, ``RStudio`` es una interfaz gráfica que utiliza, facilita y aumenta la potencialidad de ``R``.

## ¿Por qué RStudio?
La mecánica y funciones de ``Git`` pueden ser difíciles de entender si la primera aproximación que tenemos es a través del Terminal del computador. Sobre todo si no tenemos familiaridad con la Terminal.

Para reducir la complejidad que supone enfrentarse a ``Git`` y la Terminal por primera vez, la primera parte del curso se desarrolla utilizando ``Git`` a través de ``RStudio``. Sin embargo, existen herramientas de ``Git`` que sólo pueden ser utilizadas mediante Terminal. La parte del curso que trata estas herramientas se desarrolla exclusivamente utilizando la Terminal.

## Instalación ``R`` y ``RStudio``

### Ya tengo RStudio
Si ya tienes R y RStudio (ahora mismo no es importante cuál es la diferencia entre ambos. Si tienes RStudio probablemente tienes R) sólo asegurate de tener la última versión en `Help > Check for Updates`. Si no tienes la última versión presiona `Quit and Download`, esto cerrará RStudio y te llevará a la página donde podrás encontrar la última versión. En ella debes bajar hasta la sección `Installers for Supported Platforms`.  

### No tengo RStudio
Si no tienes R ni RStudio tendrás que instalar ambos.  

- Descarga e instala R desde aquí  
<https://cloud.r-project.org>.  
- Descarga e instala RStudio desde aquí (debes avanzar hasta la sección `Desktop Version`)  
<https://www.rstudio.com/products/rstudio/download/preview/> 

Una vez que hayas instalado ambos, abre RStudio y ejecuta la siguiente linea en la consola:  
`update.packages(ask = FALSE, checkBuilt = TRUE)`