---
title: "Sobre Terminal"
output: html_document
---

Traducción con leves modificaciones de <http://happygitwithr.com/shell.html#shell>

## La Terminal

Puede que te acostumbres a desarrollar la mayoría de tu trabajo utilizando algún cliente gráfico, como RStudio o GitKraken, sin embargo, en algún momento necesitas utilizar la terminal para liberar todas las potencialidades de Git. También es posible que en el futuro prefieras utilizar únicamente la terminal para desarrollar tu trabajo con Git.

### Qué es la terminal?

La terminal (a pesar de que no son exactamente lo mismo, también puedes referirte a la terminal como `shell`, `linea de comandos`, `consola`).  
La terminal te permite trabajar de forma rápida, concisa, aunque algo abstracta en comparación con cualquier interfaz gráfica. En el caso de que utilices una interfaz gráfica, la terminal realiza todo el trabajo tras los clicks en la interfaz gráfica.

### Iniciando la terminal

En Rstudio pueden abrir la terminal a través de _Tools > Terminal_ o _Tools > Shell_. La diferencia es que el primero abre una terminal dentro de RStudio, mientras que la segunda abre una terminal externa a RStudio. En ambos casos lo más probable es que la terminal utilice el directerior del proyecto para inciciar la terminal.  
En la terminal podrás ver el nombre del usuario y grupo con el que se ha iniciado la terminal y luego el directorio actual.

### Windows, la manzana podrida

#### Git Bash

En Windows tienes al meno 4 posible terminales que puedes usar. Sin entrar en demasiado detalle, siempre querrás utilizar la terminal `Git Bash`.  
En el mejor de los mundos posibles esta será la terminal que RStudio abrirá cuando inicies la terminal.

En la ventana debería decir `MSYS` (o `MINGW64`) al comienzo de izquierda a derecha.  

Si vez una ventana distinta al iniciar la terminal desde RStudio, puedes cambiar el comportamiento que RStudio tiene con la terminal en _Tools > Global > Options > Terminal_. En caso de que no aparezca `Git Bash` entre las opciones probablemente ha salido algo mal en la instalación de Git.

#### Command prompt

Esta es la terminal nativa de Windows. Si vez en la ventana `cmd.exe` has dado con la terminal incorrecta.

#### Power shell

Otra terminal, más moderna que el `Command prompt`, es el `Power Shell`. Si puedes vez `powershell.exe` en la ventana es porque has dado con esta terminal.



