--- 
title: "Learn2Git. Introducción a Git y Github"
author: ""
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "Curso de Git"
---

# Sobre Learn2Git

Este curso tiene por objetivo dar una introducción breve y práctica al uso de ``Git`` y ``Github``. Cada una de las secciones contiene una breve explicación y los pasos (incluyendo código) a seguir para lograr cada una de las tareas que se plantean.

Si bien la primera parte del curso se desarrolla utilizando ``R`` y ``RStudio``, estas herramientas no son necesarias para el uso de ``Git`` ni de ``Github``. Otras plataformas, como ``MATLAB``, cuentan con sus propias integraciones de ``Git``. En cualquier caso, ``Git`` puede ser utilizado de forma autonoma utilizando la terminal del computador, o alguna interfaz gráfica como ``GitKraken``.

No es necesario tener conocimiento acabado sobre ``R``, ``RStudio``, ni sobre programación para completar el curso. Sí es deseable (aunque no estrictamente necesario) tener alguna familiaridad con programación.