---
title: "README"
author: ""
date: "June 10, 2018"
output: html_document
---

Este repositorio contiene contiene un curso introductorio y medio-ish a Git. El curso puede ser seguido (idealmente) en su totalidad, o bien sus capítulos pueden ser usados de forma aislada (ya que estos están autocontenidos).

Actualmente existen muchos cursos de Git gratis y abiertos en internet (vease ...), sin embargo, la mayoría de ellos están en inglés. Con el objetivo de facilitar la introducción a esta herramienta he creado este curso a partir de otros cursos en inglés. Cada uno de los capítulos o secciones que han sido tomados de otros cursos están debidamente citados al comienzo de cada capítulo o sección. Los cambios que he hecho sobre el material original consisten principalmente en la traducción al español y la adaptación para acomodar los contenidos a los objetivos que planteado para este curso.

El repositorio es mantenido principalmente por mi y recibe ayuda de otros colaboradores. Los errores que puedan haber en alguna de las secciones de este repositorio (imágenes, redacción, código, etc.) pueden ser reportados como `Issue`.

El repositorio es, y sigue siendo, un trabajo en progreso.