---
title: "Git y tu, una historia de amor"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```











## Git y Github, otra historia de amor.

Git permite llevar registro y control sobre los cambios que realizamos sobre un repositorio. GitHub es una plataforma online que permite almacenar repositorios de forma remota (en la internets). Las cuentas gratuitas de GitHub permiten tener un número ilimitado de repositorios públicos. Para utilizar repositorios privados se puede o bien pagar una subscripción, o solicitar cuentas premium para estudiantes u otras organizaciones.

## Cuenta GitHub

Primero partiremos creando una cuenta gratis en [GitHub](http://github.com). Necesitaremos:  
  
- Nombre de usuario  
- Correo electrónico  
- Contraseña  



## Conectando con GitHub  

Esta parte tiene por objetivo ver si pueden hacer pull y push de GitHub a sus computadores.

### Crea un repositorio en GitHub  

Asegurate de haber ingresado a tu cuenta en [GitHub](https://github.com).  
Crea un nuevo repositorio presionando el botón verde "New repository", o, si estás en la página de tu perfil, debes ir a "Repositories" y luego "New".  

El nombre del repositorio será: `newrepo`. Además marcaremos la opción "Initialize this repository with a README". Para crear el repositorio seleccionamos "Create repository".  

Para usar este repositorio de forma local vamos a copiar la dirección HTTPS presionando el botón verde "Clone or Download". Ahí debería aparecer una dirección que comienza con `https://`. Si en cambio aparece una dirección que comienza con `git@github.com`, presiona en la esquina superior derecha donde dice `Use HTTPS`.


### Clona el repositorio a un computador local

Escoge una carpeta donde quieres ubicar tu repositorio y asegurate de encontrarte en esa carpeta desde la consola. Puedes usar `pwd` en la consola para saber en que carpeta de encuentras. Para ir de una carpeta a otra puedes utilizar `cd` (por ejemplo `cd ~/Documentos`).

Para clonar el repositorio usaremos el enlace que copiamos anteriormente y ejecutaremos el siguiente codigo en la consola:  
`git clone enlace_al_repositorio`  
En mi caso el comando se ve así:  
`git clone https://github.com/nik0lai/newrepo.git`  

Al correr la linea (si todo sale bien) deberían ver algo así en la consola.

```
Cloning into 'myrepo'...
remote: Counting objects: 3, done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), done.
Checking connectivity... done.

```
### Cambio, commit y push

Estas son las tres acciones que realizarás la mayor cantidad de veces cuando trabajes con Git.  
Para ilustrar estas acciones vamos a agregar una linea de texto al archivo README.md que se encuentra en el repositorio que hemos creado anteriormente. Agregaremos esta nueva linea directamente desde la consola (esta linea de comando no devolverá nada a la consola):

`echo "Escribí este linea localmente desde mi computador" >> README.md`  

Tambien, pueden simplementa abrir el archivo con algún procesador de texto (como gedit, notepad, etc.), agregar una linea de texto manualmente al final del documento y guardar el archivo.

Siempre que hagamos cambios en los archivos que se encuentran dentro del repositorio podremos ver qué archivos han sido modificados utilizando `git status` en la consola.  

En la consola debería aparecer algo así:  
```
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   README.md

no changes added to commit (use "git add" and/or "git commit -a")
```

Ahora haremos commit a nuestro cambio y lo pushearemos (subiremos) al repositorio remoto que se encuentra en GitHub.  
Primero agregaremos los archivos que queremos agregar a nuestro commit, luego haremos commit, y por último, pushearemos el commit:  

```
git add README.md  
git commit -m "Commit hecho desde mi ordenadora local"  
git push origin master  
```

En este ejemplo `-m` es un indicador (o flag) que indica que lo que viene a continuación es un mensaje que será incluido como etiqueta del commit. Git requiere que cada commit tenga un mensaje que indique información sobre los cambios asociados al commit. Si olvidas agregar `-m` a `git commit` git solicitará mediante una terminal de texto un mensaje para el commit.  

Los mensajes asociados a los commit deben dar información clara y concisa sobre los cambios que incluye el commit. Estos mensajes debieran ser claros para ti en el futuro y para otros colaboradores.

### Han llegado mis cambios y commits al repositorio remoto en GitHub?

En tu explorar de internet entra a tu repositorio en [GitHub](https://github.com). Ahí deberías ver la línea que hemos ingresado localmente en nuestro computador ("Escribí este linea localmente desde mi computador").  
Si seleccionas "commits" verás un commit con el mensaje que hemos ingresado en la consola al hacer commit ("Commit hecho desde mi computadora local").

## Configuración de credenciales

Para evitar escribir el nombre de usuario y la contraseña cada vez que nos conectamos podemos almacenar nuestra información en cache. Utilizaremos HTTPS (no llaves SSH) debido a que su configuración es mucho más simple y es el método de autenticación recomendado por GitHub.

Para almacenar la información en cache necesitamos un repositorio que exista local y remotamente, por lo que usaremos el repositorio que hemos creado.

### Git credential helper

Con el siguiente comando en la terminal podemos revisar si el git instalado es lo suficientemente nuevo para tener `credential helper`.
```
git --version
```
### Activa el credential helper

#### Windows

En la consola ejecuta el siguiente comando:  
```
git config --global credential.helper wincred
```

#### Mac

En la consola ejecuta el siguiente comando:  
```
git credential-osxkeychain
```
Deberías ver algo así:
```
git credential-osxkeychain
```

#### Linux

En la consola ejecuta el siguiente comando:
```
git config --global credential.helper 'cache --timeout=10000000'
```

### Haz que Git te pida tu usuario y contraseña

Para hacer que Git nos pida nuestros datos tendremos que hacer un cambio, un commit, e intentar hacer push a ese commit. Las siguientes lineas harán el trabajo:

```
echo "nueva linea!" >> README.md
git add -A
git commit -m "nuevo commit desde mi computador"
git push -u origin master
```

Si todo sale bien, git nos pedirá nuestros datos por última vez. Puedes cerciorarte si los cambios han tenido efecto ejecutando las siguientes lineas.

```
echo "OTRA nueva linea!" >> README.md
git add -A
git commit -m "OTRO nuevo commit desde mi computador"
git push origin master
```

Si Git no te ha pedido tus datos esta vez puedes declararte victorioso.